---
kind: pipeline
name: ansible
type: docker
platform:
  os: linux
  arch: arm64


steps:
  - name: build-ansible
    image: plugins/docker
    settings:
      repo: ktruckenmiller/ansible
      username:
        from_secret: username
      password:
        from_secret: password
      tags:
        - ${DRONE_COMMIT}
        - arm
    when:
      branch: [master]
      event: [push]
