pipeline:
  build_friend:
    image: plugins/docker
    repo: ktruckenmiller/ansible
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT}
      - latest
    when:
      branch: [master]
      event: [push]
